version: "3.4"

services:
  postgres:
    container_name: mediasoup-express-db
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mediasoup-express
      POSTGRES_PASSWORD: mediasoup-express

volumes:
  postgres_data: